// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCquVbq3NlBOcDdBHKpUTccMhk9ZOvHlhc',
    appId: '1:582390636327:web:b5c7c5c98613d27a465302',
    messagingSenderId: '582390636327',
    projectId: 'task2-6e48c',
    authDomain: 'task2-6e48c.firebaseapp.com',
    storageBucket: 'task2-6e48c.firebasestorage.app',
    measurementId: 'G-JYEHPV71YW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGnD8PATcuEkiEnjaqMAV9QBcfy1Ll0_o',
    appId: '1:582390636327:android:86bdfb87f39f98cd465302',
    messagingSenderId: '582390636327',
    projectId: 'task2-6e48c',
    storageBucket: 'task2-6e48c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwYIsPCTSabeooIkbE784Ucd10uCViifo',
    appId: '1:582390636327:ios:1f08d763fdedd0ae465302',
    messagingSenderId: '582390636327',
    projectId: 'task2-6e48c',
    storageBucket: 'task2-6e48c.firebasestorage.app',
    iosBundleId: 'com.example.task2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwYIsPCTSabeooIkbE784Ucd10uCViifo',
    appId: '1:582390636327:ios:1f08d763fdedd0ae465302',
    messagingSenderId: '582390636327',
    projectId: 'task2-6e48c',
    storageBucket: 'task2-6e48c.firebasestorage.app',
    iosBundleId: 'com.example.task2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCquVbq3NlBOcDdBHKpUTccMhk9ZOvHlhc',
    appId: '1:582390636327:web:511004e50e30009a465302',
    messagingSenderId: '582390636327',
    projectId: 'task2-6e48c',
    authDomain: 'task2-6e48c.firebaseapp.com',
    storageBucket: 'task2-6e48c.firebasestorage.app',
    measurementId: 'G-RN133MWGFG',
  );
}
